### ISSUE TITLE
Could you link to this GitHub site from your CRAN page and vice versa?

### ISSUE THREAD

**Issue by dvg-p4** [insitro/AllelicSeries#25]
To do the former, I think you just need to insert a "URL" line in your "DESCRIPTION" file, like such:

https://github.com/tidyverse/ggplot2/blob/e594b49fdd5e4d95bf1031edaf6c7ccfc0cdedb0/DESCRIPTION#L30-L31

And for the latter you can add this line to your README:

https://github.com/tidyverse/ggplot2/blob/e594b49fdd5e4d95bf1031edaf6c7ccfc0cdedb0/README.md?plain=1#L9

(Of course, substitute AllelicSeries for ggplot2 on these lines)

**Comment by zmccaw-insitro** [comment]
Thanks for the suggestions, Dan! The proposed changed have been merged.
