### ISSUE TITLE
Feature request: Allow more than three weighting categories

### ISSUE THREAD

**Issue by dvg-p4** [insitro/AllelicSeries#27]
e.g. say I want to have four categories, with separate weights for "benign missense", "damaging missense", "low-confidence LoF", and "HC LoF". Or 5, with a weight for "splice variant", etc. etc.

It looks like the three documented categories are currently hardcoded, but I think the logic should be generalizable. If this isn't something you're planning to work on, I might try putting together a fork and/or PR to support it.

**Comment by zmccaw-insitro** [comment]
Hi Dan, great suggestion. Yes, this is something we had considered and plan to implement. I'm away for ASHG this week, but hope to follow-up with an update soon.

**Comment by zmccaw-insitro** [comment]
Hi Dan, as of version 1.1.0 (merged today, 11/14/24), both `COAST` and `COASTSS` allow for an arbitrary number of annotation categories. To do so, annotate the variants with integer labels in `c(1, ..., L)`, where `L` is the total number of categories, then when performing the analysis, supply COAST(-SS) with a weight vector of corresponding length `L`. Please let us know how it goes!
